# Generated by Django 4.2.10 on 2024-02-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
    ]
