# Generated by Django 4.2.10 on 2024-02-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_recipe_comments_remove_recipe_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeComment',
        ),
    ]
