# Generated by Django 4.2.10 on 2024-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_delete_recipecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.TextField(default='www.mywebsite.com'),
            preserve_default=False,
        ),
    ]
