# Generated by Django 4.2.10 on 2024-04-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_recipe_ingredients_recipe_ingredient1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
