# Generated by Django 4.2.10 on 2024-04-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_recipe_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='api',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
