# Generated by Django 4.2.10 on 2024-04-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_recipe_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apiId', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='api',
        ),
    ]
