# Generated by Django 4.2.10 on 2024-04-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_apimeal_steps_alter_apimeal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient10',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient11',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient12',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient13',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient14',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient15',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient16',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient17',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient18',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient19',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient20',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient4',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient5',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient6',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient7',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient8',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient9',
        ),
    ]
