# Generated by Django 4.2.10 on 2024-04-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_ingredient_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement',
        ),
    ]
