# Generated by Django 4.2.10 on 2024-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_ingredient_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='Unidentified', max_length=100),
        ),
    ]
