# Generated by Django 4.2.10 on 2024-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimeal',
            name='author',
            field=models.CharField(default='Unidentified', max_length=100),
        ),
    ]
