# Generated by Django 4.2.10 on 2024-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_apimeal_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimeal',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
