# Generated by Django 4.2.10 on 2024-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_apimeal_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimeal',
            name='image',
            field=models.TextField(max_length=300),
        ),
    ]
